# Generated by Django 2.1.2 on 2018-11-01 05:30

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0002_auto_20181031_2209'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('cat_id', models.IntegerField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=300, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medicines',
            fields=[
                ('med_id', models.IntegerField(primary_key=True, serialize=False)),
                ('med_name', models.CharField(max_length=300, unique=True)),
                ('med_image', models.ImageField(blank=True, upload_to='administrator/static/Medicines/')),
                ('cat_id', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='administrator.Category')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.IntegerField(primary_key=True, serialize=False)),
                ('batch_no', models.TextField(max_length=100)),
                ('mfd_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('quantity', models.IntegerField()),
                ('med_id', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='administrator.Medicines')),
            ],
        ),
    ]
