# Generated by Django 2.1.2 on 2018-11-02 06:28

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0003_category_medicines_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doct_id', models.IntegerField(primary_key=True, serialize=False)),
                ('doct_name', models.CharField(max_length=300, unique=True)),
                ('qualification', models.TextField(max_length=600)),
                ('specializations', models.TextField(max_length=300)),
                ('doct_des', models.TextField(max_length=6000000, unique=True)),
                ('doct_image', models.ImageField(blank=True, upload_to='administrator/static/Doctors/')),
                ('status', models.TextField(max_length=100)),
                ('dep_id', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='administrator.Departments')),
            ],
        ),
    ]
