# Generated by Django 2.1.2 on 2018-11-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0004_doctor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='quantity',
            new_name='price',
        ),
        migrations.AddField(
            model_name='stock',
            name='stock',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='cat_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='departments',
            name='dep_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='doct_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='medicines',
            name='med_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='stock',
            name='batch_no',
            field=models.TextField(max_length=20),
        ),
        migrations.AlterField(
            model_name='stock',
            name='stock_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
