# Generated by Django 2.1.2 on 2018-11-08 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0007_auto_20181108_1446'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='med_id',
            new_name='med_name',
        ),
    ]
