# Generated by Django 2.1.2 on 2018-11-08 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0008_auto_20181108_1455'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='med_name',
        ),
        migrations.DeleteModel(
            name='Stock',
        ),
    ]
