# Generated by Django 2.1.2 on 2018-11-08 17:52

from django.db import migrations, models
import django.db.models.fields.related


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0009_auto_20181108_2318'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('stock_id', models.AutoField(primary_key=True, serialize=False)),
                ('stock_name', models.TextField(max_length=50)),
                ('batch_no', models.TextField(max_length=20)),
                ('mfd_date', models.DateField()),
                ('exp_date', models.DateField()),
                ('price', models.IntegerField()),
                ('stock', models.IntegerField()),
                ('med_id', models.ForeignKey(on_delete=django.db.models.fields.related.ForeignKey, to='administrator.Medicines')),
            ],
        ),
    ]
