# Generated by Django 2.1.3 on 2018-11-18 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administrator', '0011_saveappointment'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField(max_length=50)),
                ('password', models.TextField(max_length=50)),
                ('role', models.TextField(max_length=50)),
            ],
        ),
    ]
